spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/users/**
        - id: authorservice
          uri: lb://authorservice
          predicates:
            - Path=/api/authors/**
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
