server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/users/**
        - id: author
          uri: lb://AUTHOR
          predicates:
            - Path=/api/authors/**
        - id: journal
          uri: lb://JOURNAL
          predicates:
            - Path=/api/articles/**
        - id: comment
          uri: lb://COMMENT
          predicates:
            - Path=/api/comments/**
        - id: media
          uri: lb://MEDIA
          predicates:
            - Path=/api/media/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
