server:
  port: 8080
spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework: DEBUG
    com.netflix: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.filter.ratelimit: TRACE
